version: '3'
services:
  # Spring Boot application
  web:
    image: crochet
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3307/testDB

  # MySQL database
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
