spring:
  profiles:
    active: local

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 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
            clientSecret: 782330301173-u95n2p5pc6obg6nim17bq7m4kmm861tt.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: phanvanluom97bd@gmail.com
    password: bnptvnwccmxgwuxq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 100MB

app:
  auth:
    tokenSecret: 37e2a786c5dc962fac3cfcf5c72b592339abbd7433148e8ed2dd0fc13f1d7402a53de020cb3b0b75f534b9937e191943f3feff64c88af6fbb3eb9e47dccadfa2
    tokenExpirationMs: 900000 # 15 minutes
    refresh-token-expiration-ms: 86400000 # 1 day
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

authorize:
  http-request:
    authenticated:
      - "/blog/create"
      - "/comment/create"
      - "/free-pattern/create"
      - "/pattern/create"
      - "/pattern/detail"
      - "/category/create"
      - "/category/update"
      - "/category-pattern/create"
      - "/category-pattern/update"
      - "/category-free-pattern/create"
      - "/category-free-pattern/update"
      - "/firebase-storage/upload-file"
      - "/product/create"
      - "/users/**"
      - "/banner/batchInsertOrUpdate"
      - "/bannerType/**"
    permit-all:
      - "/"
      - "/auth/**"
      - "/oauth2/**"
      - "/error"
      - "/favicon.ico"
      - "/*.png"
      - "/*.gif"
      - "/*.svg"
      - "/*.jpg"
      - "/*.html"
      - "/*.css"
      - "/*.js"
      - "/swagger-ui/**"
      - "/swagger-ui.html"
      - "webjars/**"
      - "/v3/api-docs/**"
      - "/v3/api-docs"
      - "/swagger-resources"
      - "/swagger-resources/**"