spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: false

paypal:
  username: ${PAYPAL_CLIENT_ID}
  password: ${PAYPAL_CLIENT_SECRET}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  username: default
  password: ${REDIS_PASSWORD}
