spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/testDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

paypal:
  username: ${PAYPAL_CLIENT_ID}
  password: ${PAYPAL_CLIENT_SECRET}

