spring:
  profiles:
    active: ${ENV}

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: phanvanluom97bd@gmail.com
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false

  servlet:
    multipart:
      max-file-size: 100MB

app:
  auth:
    tokenSecret: ${TOKEN_SECRET}
    tokenExpirationMs: 900000 # 15 minutes
    refresh-token-expiration-ms: 86400000 # 1 day
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

paypal:
  username: ${PAYPAL_CLIENT_ID}
  password: ${PAYPAL_CLIENT_SECRET}

azure:
  storage:
    azure-storage-connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    azure-storage-container-name: crochetcontainers