spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/testDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/liquibase/db.changelog-master.yaml
    enabled: ${LIQUIBASE_ENABLED:false}
    user: root
    password: root
    url: jdbc:mysql://localhost:3306/testDB
    drop-first: ${DROP_ENABLED:false}

paypal:
  username: ${PAYPAL_CLIENT_ID}
  password: ${PAYPAL_CLIENT_SECRET}