spring:
  profiles:
    active: ${env:dev}

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 100MB

# Application configuration
app:
  auth:
    tokenSecret: ${TOKEN_SECRET}
    tokenExpirationMs: 900000 # 15 minutes
    refresh-token-expiration-ms: 86400000 # 1 day
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - https://tieuphuongcrochet.com/oauth2/redirect
      - https://littlecrochet.web.app/oauth2/redirect
      - https://littlecrochet.firebaseapp.com/oauth2/redirect

# Authorization configuration
authorize:
  http-request:
    allowedOrigins: ${ALLOWED_ORIGINS}
    authenticated:
      - "/blog/create"
      - "/comment/create"
      - "/free-pattern/create"
      - "/pattern/create"
      - "/pattern/detail"
      - "/category/create"
      - "/category/update"
      - "/category-pattern/create"
      - "/category-pattern/update"
      - "/category-free-pattern/create"
      - "/category-free-pattern/update"
      - "/firebase-storage/upload-file"
      - "/product/create"
      - "/users/**"
      - "/banner/batchInsertOrUpdate"
      - "/bannerType/**"
      - "/blog-categories/create"
      - "/blog-categories/update"
      - "/blog-categories/delete/**"
      - "/setting/**"

# Firebase configuration
firebase:
  serviceAccountKey: ${SERVICE_ACCOUNT_KEY}

# Logging configuration
logging:
  level:
    org.crochet: DEBUG
    org.springframework.web: DEBUG
    root: INFO

# Resilience4j configuration
resilience4j:
  ratelimiter:
    instances:
      passwordResetRateLimiter:
        limitForPeriod: 1
        limitRefreshPeriod: 3m
        timeoutDuration: 5s
      resendEmail:
        limitForPeriod: 3
        limitRefreshPeriod: 1h
        timeoutDuration: 0s
  retry:
    instances:
      resendEmail:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - org.springframework.mail.MailException
