name: Azure Web App Deploy

env:
  AZURE_WEBAPP_NAME: your-app-name

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ github.workspace }}build/libs/*.jar
          retention-days: 1

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    name: Deploy to Staging
    needs: build
    environment:
      name: 'Staging'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
