name: Docker deployment

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build & push Docker image
    environment: littlecrochet
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Build and push
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          build-args: |
            AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/crochet:latest
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}