name: Docker deployment

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build & push Docker image
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Build and push
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            EMAIL=${{ secrets.EMAIL }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}
            APP_PASSWORD=${{ secrets.APP_PASSWORD }}
            PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}
            PAYPAL_CLIENT_SECRET=${{ secrets.PAYPAL_CLIENT_SECRET }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/crochet:latest
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}