name: Heroku Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    environment:
      name: 'littlecrochet'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ vars.HEROKU_APP }}
          heroku_email: ${{ vars.HEROKU_EMAIL }}
        env:
          ENV: ${{ vars.ENV }}
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}