name: Heroku Deployment

on:
  workflow_run:
    workflows: [ "Build on Production" ]
    types:
      - completed
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    environment: little-crochet-prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}