name: Build

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
      - 'release'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Gradle build
        env:
          ENV: ${{ vars.ENV }}
          DB_URL: ${{ vars.DB_URL }}
          DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          GITHUB_ACTOR: ${{ secrets.GIT_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
          PAYPAL_CLIENT_SECRET: ${{ secrets.PAYPAL_CLIENT_SECRET }}
        run: |
          chmod +x gradlew
          ./gradlew build