name: Build

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
      - 'release'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    environment: littlecrochet
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle build
        env:
          ENV: ${{ vars.ENV }}
          DB_URL: ${{ vars.DB_URL }}
          DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: |
          chmod +x gradlew
          ./gradlew build
  docker:
    needs: build
    runs-on: ubuntu-latest
    name: Build & push Docker image
    environment: littlecrochet
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Build and push
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/crochet:latest
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}